"""first migration

Revision ID: 16a1d35983e6
Revises: 0f662a79357f
Create Date: 2025-12-25 14:42:25.064102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a1d35983e6'
down_revision: Union[str, Sequence[str], None] = '0f662a79357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_profile', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('model_profile_user_id_fkey'), 'model_profile', type_='foreignkey')
    op.create_foreign_key(None, 'model_profile', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_profile', type_='foreignkey')
    op.create_foreign_key(op.f('model_profile_user_id_fkey'), 'model_profile', 'users', ['user_id'], ['id'])
    op.alter_column('model_profile', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
