"""first migration

Revision ID: 2f5225924c07
Revises: 8979c30196e1
Create Date: 2025-12-25 14:34:49.165198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5225924c07'
down_revision: Union[str, Sequence[str], None] = '8979c30196e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_profile', sa.Column('user_uuid', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('model_profile_user_id_key'), 'model_profile', type_='unique')
    op.create_unique_constraint(None, 'model_profile', ['user_uuid'])
    op.drop_constraint(op.f('model_profile_user_id_fkey'), 'model_profile', type_='foreignkey')
    op.create_foreign_key(None, 'model_profile', 'users', ['user_uuid'], ['uuid'])
    op.drop_column('model_profile', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_profile', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_profile', type_='foreignkey')
    op.create_foreign_key(op.f('model_profile_user_id_fkey'), 'model_profile', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'model_profile', type_='unique')
    op.create_unique_constraint(op.f('model_profile_user_id_key'), 'model_profile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('model_profile', 'user_uuid')
    # ### end Alembic commands ###
