"""first migration

Revision ID: 3777e2d0bf08
Revises: acde2333e3d6
Create Date: 2025-12-25 14:40:06.611801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3777e2d0bf08'
down_revision: Union[str, Sequence[str], None] = 'acde2333e3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('model_profile_user_id_fkey'), 'model_profile', type_='foreignkey')
    op.create_foreign_key(None, 'model_profile', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_profile', type_='foreignkey')
    op.create_foreign_key(op.f('model_profile_user_id_fkey'), 'model_profile', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
