"""rename basic info

Revision ID: 62fe61b9cc15
Revises: e6b53a4e0141
Create Date: 2025-12-25 11:24:42.115210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fe61b9cc15'
down_revision: Union[str, Sequence[str], None] = 'e6b53a4e0141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_professional_id'), 'model_professional', ['id'], unique=False)
    op.drop_constraint(op.f('model_professional_user_id_fkey'), 'model_professional', type_='foreignkey')
    op.create_foreign_key(None, 'model_professional', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('home_town', sa.String(), nullable=True))
    op.drop_column('users', 'home_city')
    op.drop_column('users', 'languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('home_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'home_town')
    op.drop_constraint(None, 'model_professional', type_='foreignkey')
    op.create_foreign_key(op.f('model_professional_user_id_fkey'), 'model_professional', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_model_professional_id'), table_name='model_professional')
    # ### end Alembic commands ###
