"""initial schema

Revision ID: 689e9eaf6116
Revises: 
Create Date: 2025-12-22 23:30:49.797679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689e9eaf6116'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('home_slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('slider_title', sa.String(length=255), nullable=True),
    sa.Column('slider_type', sa.Integer(), nullable=False),
    sa.Column('is_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_home_slider_id'), 'home_slider', ['id'], unique=False)
    op.create_table('model_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height_min', sa.Float(), nullable=True),
    sa.Column('height_max', sa.Float(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('age_range_min', sa.Integer(), nullable=True),
    sa.Column('age_range_max', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('skin_tone', sa.String(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_filters_gender'), 'model_filters', ['gender'], unique=False)
    op.create_index(op.f('ix_model_filters_id'), 'model_filters', ['id'], unique=False)
    op.create_table('model_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_video_user_id'), 'model_video', ['user_id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('other_title', sa.String(length=255), nullable=True),
    sa.Column('is_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('current_city', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('home_city', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('phone', name='uq_users_phone'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('work_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('work_type', sa.String(length=255), nullable=False),
    sa.Column('is_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_work_type_id'), 'work_type', ['id'], unique=False)
    op.create_table('agency_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_agency_profile_id'), 'agency_profile', ['id'], unique=False)
    op.create_table('contact_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('banner_title', sa.String(length=255), nullable=False),
    sa.Column('banner_description', sa.Text(), nullable=False),
    sa.Column('banner_image', sa.String(length=500), nullable=False),
    sa.Column('contact_info_email', sa.String(length=150), nullable=False),
    sa.Column('contact_info_phone', sa.String(length=150), nullable=False),
    sa.Column('contact_info_day', sa.String(length=250), nullable=False),
    sa.Column('contact_info_time', sa.String(length=150), nullable=False),
    sa.Column('contact_form_image', sa.String(length=500), nullable=False),
    sa.Column('contact_form_title', sa.String(length=100), nullable=False),
    sa.Column('contact_form_small_desc', sa.String(length=150), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_contact_banner_id'), 'contact_banner', ['id'], unique=False)
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('pay_min', sa.Float(), nullable=True),
    sa.Column('pay_max', sa.Float(), nullable=True),
    sa.Column('pay_type', sa.String(length=50), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_job_posting_id'), 'job_posting', ['id'], unique=False)
    op.create_table('model_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_uuid', sa.UUID(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_uuid'], ['model_video.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_uuid', 'image_index')
    )
    op.create_index(op.f('ix_model_images_media_uuid'), 'model_images', ['media_uuid'], unique=False)
    op.create_table('model_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_body_front', sa.String(), nullable=True),
    sa.Column('full_body_left_side', sa.String(), nullable=True),
    sa.Column('full_body_right_side', sa.String(), nullable=True),
    sa.Column('head_shot', sa.String(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('introduction_video', sa.String(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_media_id'), 'model_media', ['id'], unique=False)
    op.create_table('model_professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_experience', sa.Boolean(), nullable=True),
    sa.Column('experience_details', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'professional', 'expert', name='experiencelevelenum'), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interested_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('willing_to_travel', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_professional_id'), 'model_professional', ['id'], unique=False)
    op.create_table('model_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('chest_bust', sa.String(length=100), nullable=True),
    sa.Column('waist', sa.String(length=100), nullable=True),
    sa.Column('hips', sa.String(length=100), nullable=True),
    sa.Column('shoulder', sa.String(length=100), nullable=True),
    sa.Column('shoe_size', sa.String(length=100), nullable=True),
    sa.Column('chest_size', sa.String(length=100), nullable=True),
    sa.Column('suit_jacket_size', sa.String(length=100), nullable=True),
    sa.Column('bust_cup_size', sa.String(length=100), nullable=True),
    sa.Column('dress_size', sa.String(length=100), nullable=True),
    sa.Column('top_size', sa.String(length=100), nullable=True),
    sa.Column('bottom_size', sa.String(length=100), nullable=True),
    sa.Column('complexion', sa.String(length=255), nullable=True),
    sa.Column('eye_color', sa.String(length=255), nullable=True),
    sa.Column('hair_color', sa.String(length=255), nullable=True),
    sa.Column('body_type', sa.String(length=255), nullable=True),
    sa.Column('body_shape', sa.String(length=255), nullable=True),
    sa.Column('hair_length', sa.String(length=255), nullable=True),
    sa.Column('facial_har', sa.String(length=255), nullable=True),
    sa.Column('tattoos_piercings', sa.Boolean(), nullable=True),
    sa.Column('tattoos_details', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_profile_id'), 'model_profile', ['id'], unique=False)
    op.create_table('model_protfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_protfolio_id'), 'model_protfolio', ['id'], unique=False)
    op.create_table('user_social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_social_links_id'), 'user_social_links', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('selected_media', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_user_social_links_id'), table_name='user_social_links')
    op.drop_table('user_social_links')
    op.drop_index(op.f('ix_model_protfolio_id'), table_name='model_protfolio')
    op.drop_table('model_protfolio')
    op.drop_index(op.f('ix_model_profile_id'), table_name='model_profile')
    op.drop_table('model_profile')
    op.drop_index(op.f('ix_model_professional_id'), table_name='model_professional')
    op.drop_table('model_professional')
    op.drop_index(op.f('ix_model_media_id'), table_name='model_media')
    op.drop_table('model_media')
    op.drop_index(op.f('ix_model_images_media_uuid'), table_name='model_images')
    op.drop_table('model_images')
    op.drop_index(op.f('ix_job_posting_id'), table_name='job_posting')
    op.drop_table('job_posting')
    op.drop_index(op.f('ix_contact_banner_id'), table_name='contact_banner')
    op.drop_table('contact_banner')
    op.drop_index(op.f('ix_agency_profile_id'), table_name='agency_profile')
    op.drop_table('agency_profile')
    op.drop_index(op.f('ix_work_type_id'), table_name='work_type')
    op.drop_table('work_type')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_model_video_user_id'), table_name='model_video')
    op.drop_table('model_video')
    op.drop_index(op.f('ix_model_filters_id'), table_name='model_filters')
    op.drop_index(op.f('ix_model_filters_gender'), table_name='model_filters')
    op.drop_table('model_filters')
    op.drop_index(op.f('ix_home_slider_id'), table_name='home_slider')
    op.drop_table('home_slider')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
