"""update model_profile

Revision ID: 6c8b9ba84c85
Revises: 71d5d19c2565
Create Date: 2025-12-24 16:15:25.181196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8b9ba84c85'
down_revision: Union[str, Sequence[str], None] = '71d5d19c2565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('chest_bust', sa.String(length=100), nullable=True),
    sa.Column('waist', sa.String(length=100), nullable=True),
    sa.Column('hips', sa.String(length=100), nullable=True),
    sa.Column('shoulder', sa.String(length=100), nullable=True),
    sa.Column('shoe_size', sa.String(length=100), nullable=True),
    sa.Column('complexion', sa.String(length=255), nullable=True),
    sa.Column('eye_color', sa.String(length=255), nullable=True),
    sa.Column('hair_color', sa.String(length=255), nullable=True),
    sa.Column('tattoos_piercings', sa.Boolean(), nullable=True),
    sa.Column('tattoos_details', sa.String(length=255), nullable=True),
    sa.Column('suit_jacket_dress_size', sa.String(length=100), nullable=True),
    sa.Column('hair_length', sa.String(length=255), nullable=True),
    sa.Column('body_type', sa.String(length=255), nullable=True),
    sa.Column('body_shape', sa.String(length=255), nullable=True),
    sa.Column('facial_hair', sa.String(length=255), nullable=True),
    sa.Column('bust_cup_size', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_model_profile_id'), 'model_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_profile_id'), table_name='model_profile')
    op.drop_table('model_profile')
    # ### end Alembic commands ###
