"""profile models new fileds added

Revision ID: 71d5d19c2565
Revises: 689e9eaf6116
Create Date: 2025-12-24 16:05:17.860859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71d5d19c2565'
down_revision: Union[str, Sequence[str], None] = '689e9eaf6116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_posting', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_posting', 'visibility',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('job_posting', 'created_at')
    op.drop_column('job_posting', 'updated_at')
    op.add_column('model_profile', sa.Column('suit_jacket_dress_size', sa.String(length=100), nullable=True))
    op.add_column('model_profile', sa.Column('facial_hair', sa.String(length=255), nullable=True))
    op.drop_column('model_profile', 'suit_jacket_size')
    op.drop_column('model_profile', 'chest_size')
    op.drop_column('model_profile', 'bottom_size')
    op.drop_column('model_profile', 'top_size')
    op.drop_column('model_profile', 'facial_har')
    op.drop_column('model_profile', 'dress_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_profile', sa.Column('dress_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model_profile', sa.Column('facial_har', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('model_profile', sa.Column('top_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model_profile', sa.Column('bottom_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model_profile', sa.Column('chest_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('model_profile', sa.Column('suit_jacket_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('model_profile', 'facial_hair')
    op.drop_column('model_profile', 'suit_jacket_dress_size')
    op.add_column('job_posting', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('job_posting', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('job_posting', 'visibility',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_posting', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
